version: '3.0'
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "127.0.0.1:8000:80"
      - "443:443"
    stdin_open: true
    tty: true
    depends_on:
      - wordpress
    volumes:
      - wp_files:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/sites-available
    networks:
      - docker_network
  wordpress:
    build: ./requirements/wordpress
    stdin_open: true
    tty: true
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    networks:
      - docker_network
    expose:
      - 9000
  mariadb:
    build: ./requirements/mariadb
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - wp_database:/var/lib/mysql
    networks:
      - docker_network
    expose:
      - 3306
volumes:
  wp_files:
  wp_database:
networks:
  docker_network:

